language: cpp
dist: xenial
if: branch = master OR tag IS present

notifications:
  email: false

addons:
  apt:
    sources: &defSrcs
      - ubuntu-toolchain-r-test
    packages: &defPackages
      - g++-6
      - cmake
      - cmake-data
      - libminiupnpc-dev
  homebrew:
    packages:
      - miniupnpc
      - ccache
    update: true

cache:
  ccache: true
  directories:
    - ${HOME}/.cache

jobs:
  include:
    - stage: test
      os: linux
      compiler: gcc
      env: MATRIX_EVAL="CXX=g++-6 && CC=gcc-6" GCOV=gcov-6 BUILD_TYPE=Debug RTTR_COVERAGE=1
      addons:
        apt:
          sources: *defSrcs
          packages: [*defPackages, lcov]
    - os: linux
      compiler: gcc
      env: MATRIX_EVAL="CXX=g++-6 && CC=gcc-6" BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Debug
    - stage: release
      os: linux
      compiler: clang
      env: BUILD_TYPE=Release
    - os: windows
      env: BUILD_TYPE=Release

stages:
  - name: test
  - name: release

before_install:
  - eval "${MATRIX_EVAL}"
  - DEPS_DIR="${HOME}/.cache"
  - mkdir -p "${DEPS_DIR}"

install:
  - |
    export LIBUTIL_DIR="$DEPS_DIR/libutil"
    [ ! -d "$LIBUTIL_DIR/libs" ] && git clone https://github.com/Return-To-The-Roots/libutil.git "$LIBUTIL_DIR" || true
    (cd ${LIBUTIL_DIR} && git clean -fxd && git checkout master && git fetch --all && git reset --hard origin/master)

    export LIBENDIAN_DIR="$DEPS_DIR/libendian"
    [ ! -d "$LIBENDIAN_DIR/src" ] && git clone https://github.com/Return-To-The-Roots/libendian.git "$LIBENDIAN_DIR" || true
    (cd ${LIBENDIAN_DIR} && git clean -fxd && git checkout master && git fetch && git reset --hard origin/master)
  - |
    BOOST_VERSION=1.67.0 # For MSVC 2017 support
    export BOOST_ROOT="${DEPS_DIR}/boost${BOOST_VERSION}"
    export ADDITIONAL_CMAKE_FLAGS="${ADDITIONAL_CMAKE_FLAGS} -DBoost_NO_SYSTEM_PATHS=ON"
    $LIBUTIL_DIR/tools/ci/installBoost.sh "${BOOST_VERSION}" "${BOOST_ROOT}" "filesystem,system,program_options,thread,test,locale,iostreams,regex"
  - |
    if [ "${RTTR_COVERAGE}" = "1" ]; then
      # Install coveralls tool
      gem install coveralls-lcov

      export ADDITIONAL_CMAKE_FLAGS="${ADDITIONAL_CMAKE_FLAGS} -DRTTR_ENABLE_COVERAGE=ON"
    fi

script: tools/travis-ci/build.sh "${BUILD_TYPE}" "${ADDITIONAL_CMAKE_FLAGS}"

after_success:
  - |
    if [ "$RTTR_COVERAGE" = "1" ]; then
      lcov --gcov-tool $GCOV --directory build --capture --output-file coverage.info --rc lcov_branch_coverage=1 > /dev/null
      # Remove unrelated stuff
      lcov --gcov-tool $GCOV --remove coverage.info '/usr/*' '*/examples/*' "${HOME}/"'.cache/*' --output-file coverage.info > /dev/null
      # Debug output
      lcov --list coverage.info
      # Coverage.io
      bash <(curl -s https://codecov.io/bash) -f coverage.info
      # Coveralls
      coveralls-lcov coverage.info
    fi

before_deploy:
  - |
    if [[ "$TRAVIS_TAG" == v* ]] && ! [[ "$TRAVIS_TAG" == *-rc* ]]; then
      export RELEASES_PRERELEASE="false"
    else
      export RELEASES_PRERELEASE="true"
    fi
    export RELEASES_NAME="Settlers 2 Tools $TRAVIS_TAG"
    export RELEASES_TAG_NAME="$TRAVIS_TAG"
    export DPL_FILENAME="rttrUtils-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz"
  - (cd build/installed && tar -zcf "../${DPL_FILENAME}" *)

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: build/${DPL_FILENAME}
  overwrite: true
  draft: false
  prerelease: ${RELEASES_PRERELEASE}
  name: ${RELEASES_NAME}
  body: Tools for working with the S2 file formats.
  #target_commitish: ${RELEASES_TARGET_COMMITISH}
  on:
    repo: Return-To-The-Roots/libsiedler2
    condition: $TRAVIS_BUILD_STAGE_NAME == Release
    tags: true
