version: 1.0.{build}
branches:
  only:
  - master
  
os: Visual Studio 2015

configuration:
  - Debug
  - Release
  
platform:
  - Win32
  - x64
    
environment:
  global:
    BOOST_DIR: 'C:\Libraries\boost_1_65_1'
    RTTR_DISABLE_ASSERT_BREAKPOINT: 1

install:
  - git clone https://github.com/Return-To-The-Roots/libutil.git libutil
  - git clone https://github.com/Return-To-The-Roots/libendian.git libendian
  - set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%cd%\libutil;%cd%\libendian

before_build:
  - mkdir build
  - cd build
  - if "%platform%"=="Win32" set CMAKE_GENERATOR=Visual Studio 14 2015
  - if "%platform%"=="x64" set CMAKE_GENERATOR=Visual Studio 14 2015 Win64
  - cmake -G "%CMAKE_GENERATOR%" -DRTTR_ENABLE_WERROR=ON -DBOOST_ROOT="%BOOST_DIR%" ..
    
build_script: cmake --build . --config %configuration% -j3

test_script: ctest --output-on-failure -C %configuration% -j3

