name: Release

on:
  push:
  pull_request:

env:
  BOOST_VERSION: 1.72.0

defaults:
  run:
    shell: bash

jobs:
  Release:
    strategy:
      matrix:
        include:
          - { compiler: gcc-10,   os: ubuntu-18.04,  buildType: Release }
          - { compiler: msvc,     os: windows-2019, buildType: Release }

    runs-on: ${{matrix.os}}

    steps:
      - run: |
          echo "DEPS_DIR=${{runner.temp}}/.cache" >> $GITHUB_ENV
          echo "LIBUTIL_DIR=$GITHUB_WORKSPACE/external/libutil" >> $GITHUB_ENV
          echo "LIBENDIAN_DIR=$GITHUB_WORKSPACE/external/libendian" >> $GITHUB_ENV
          echo "TRAVIS_OS_NAME=${{matrix.os}}" >> $GITHUB_ENV
          echo "BOOST_ROOT=$BOOST_ROOT_1_72_0" >> $GITHUB_ENV # Windows only

      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Return-To-The-Roots/libutil
          ref: master
          path: external/libutil
      - uses: actions/checkout@v2
        with:
          repository: Return-To-The-Roots/libendian
          ref: master
          path: external/libendian
      - name: Cache dependencies
        if: "!startsWith(runner.os, 'Windows')"
        uses: actions/cache@v2
        with:
          path: ${{env.DEPS_DIR}}
          key: ${{matrix.os}}-${{env.BOOST_VERSION}}
      - name: Cache CCache
        if: "!startsWith(runner.os, 'Windows')"
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{matrix.os}}-${{matrix.compiler}}-ccache
      - name: Setup CCache
        if: "!startsWith(runner.os, 'Windows')"
        run: tools/ci/setupCCache.sh
        
      - name: Install Compiler
        if: "startsWith(runner.os, 'Linux')"
        run: |
          pkgs=${{matrix.compiler}}
          pkgs=${pkgs/gcc-/g++-}
          sudo apt install $pkgs
      - name: Setup compiler
        if: "!startsWith(runner.os, 'Windows')"
        run: tools/ci/setupCompiler.sh
        env:
          COMPILER: matrix.compiler
      - name: Install system packages (Linux)
        if: "startsWith(runner.os, 'Linux')"
        run: sudo apt install cmake cmake-data ccache libminiupnpc-dev
      - name: Install system packages (OSX)
        if: startsWith(runner.os, 'macOS')
        run: brew install ccache cmake boost miniupnpc

      - name: Install Boost
        if: "!startsWith(runner.os, 'Windows')"
        run: |
          BOOST_ROOT="${DEPS_DIR}/boost${BOOST_VERSION}"
          echo "BOOST_ROOT=${BOOST_ROOT}" >> $GITHUB_ENV
          echo "ADDITIONAL_CMAKE_FLAGS=${ADDITIONAL_CMAKE_FLAGS} -DBoost_NO_SYSTEM_PATHS=ON -DBoost_NO_BOOST_CMAKE=ON" >> $GITHUB_ENV
          $LIBUTIL_DIR/tools/ci/installBoost.sh "${BOOST_VERSION}" "${BOOST_ROOT}" "filesystem,system,program_options,thread,test,locale,iostreams,regex"

      - name: Build
        run: tools/travis-ci/build.sh "${{matrix.buildType}}" "${ADDITIONAL_CMAKE_FLAGS}"
